import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="grid grid-cols-5">
        <div className="col-span-5 h-screen overflow-y-auto bg-slate-100">{children}</div>
      </body>
    </html>
  );
}
